
# application.yml
spring:
  # jdbc??
  datasource:
    url: jdbc:mysql://localhost:3306/spring_demo?serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ?????
    # ??spring-boot-starter???https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    # ?????AnalyticDB?????https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE
    druid:
      initial-size: 2
      min-idle: 6
      # ????? ???
      #   activeCount?????????
      #   poolingCount???????????
      #   createTaskCount?????????
      max-active: 12
      # ???????????
      max-wait: 6000
      # ???????????????????????????????
      time-between-eviction-runs-millis: 2000
      # ??????????????????????
      min-evictable-idle-time-millis: 60000
      max-evictable-idle-time-millis: 90000
      # Druid???????????SQL??
      validation-query: select 1
      # ??true ??????????????testOnBorrow?false???????????????????
      test-while-idle: true
      # ??false ?????????
      test-on-borrow: false
      # ??true ???????????????????????????????
      test-on-return: false
      # ??PSCache??????????PSCache???
      # ??mysql????????
      # ?????????????PSCache???JVM????=???*PSCache?????*??PSCache??????
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 0
      # ?????????filters????????sql?????'wall'?????
      filters: stat,wall,slf4j
      # ??connectProperties?????mergeSql????SQL??
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=200;druid.stat.logSlowSql=true;druid.stat.enabled=true

      # WebStatFilter????????Druid Wiki???_??WebStatFilter
      # StatFilter???false
      web-stat-filter:
        enabled: true
        # ????
        url-pattern: /*
        # ???????
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        # ??session??
        session-stat-enable: true
        # ???1000
        session-stat-max-count: 20
        principal-cookie-name:
        principal-session-name:
        # ????url???sql??
        profile-enable: false
      # StatViewServlet????????Druid Wiki???_StatViewServlet??
      stat-view-servlet:
        # ???false
        enabled: true
        url-pattern: /druid/*
        # ????????????????????????
        reset-enable:
        login-username: knowcup
        login-password: knowcup
        # ???? ??127.0.0.1
        allow:
        deny:
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #??SQL????

